name: SimpleKit
version: 1.1
api-version: 1.16
main: ru.seriouscompany.simplekit.SimpleKit
author: Vadimka
depend: [ SCEssentials ]
commands:
  kit:
    description: Команда наборов
    usage: /kit
permissions:
  simplekit.*:
    description: Управление наборами
    default: op
    children:
      simplekit.list: true
      simplekit.give: true
      simplekit.del: true
      simplekit.set: true
      simplekit.query.check: true
      simplekit.query.del: true
  simplekit.give:
    description: Позволяет выдавать наборы
    default: op
  simplekit.list:
    description: Позволяет просматривать доступные наборы
    default: op
  simplekit.del:
    description: Позволяет удалять наборы
    default: op
  simplekit.set:
    description: Позволяет создавать наборы
    default: op
  simplekit.query.check:
    description: Позволяет просмотреть очереди наборов игрока
    default: op
  simplekit.query.del:
    description: Позволяет удалять очереди наборов игрока
    default: op