name: SimpleKit
version: 1.2
api-version: 1.16
main: ru.seriouscompany.simplekit.SimpleKit
author: Vadimka
depend: [ SCEssentials ]
commands:
  kit:
    description: Команда наборов
    usage: /kit
permissions:
  simplekit.*:
    description: Управление наборами
    default: op
    children:
      simplekit.kit.*: true
      simplekit.query.check: true
      simplekit.query.del: true
  simplekit.kit.give:
    description: Позволяет выдавать наборы
    default: op
  simplekit.kit.give.others:
    description: Позволяет выдавать наборы
    default: op
  simplekit.kit.list:
    description: Позволяет просматривать доступные наборы
    default: op
  simplekit.kit.del:
    description: Позволяет удалять наборы
    default: op
  simplekit.kit.set:
    description: Позволяет создавать наборы
    default: op
  simplekit.kit.*:
    description: Позволяет управлять наборами
    default: op
    children:
      simplekit.kit.list: true
      simplekit.kit.give: true
      simplekit.kit.give.others: true
      simplekit.kit.del: true
      simplekit.kit.set: true
  simplekit.query.check:
    description: Позволяет просмотреть очереди наборов игрока
    default: op
  simplekit.query.del:
    description: Позволяет удалять очереди наборов игрока
    default: op